# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift


name: CI-iOS

# Controls when the action will run. 
# Triggers the workflow on pull request events but only for the master branch.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        xcode-version: latest
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: xcodebuild -project WorldOfPAYBACK.xcodeproj -scheme "CI_iOS" -resultBundlePath $(BUILD_DIR)/$(SCHEME).xcresult -testPlan "CI_iOS" -only-test-configuration "English" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13" ONLY_ACTIVE_ARCH=YES test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: $(BUILD_DIR)/$(SCHEME).xcresult

    
